# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup MSBuild.exe
      run: echo “::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin”
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.2
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore Nuget packages
      run: nuget restore CSharp.sln
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Build Solution
      run: msbuild CSharp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile   
