# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@master
        
       - name: Test  
         run:
          echo "Test"
       
       - name: Install Nuget
         uses: nuget/setup-nuget@v1
         with:
          nuget-version: '5.3.1'
          
       - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
         run: nuget restore

      # Setup MSBUILD
       - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v1.0.0 
        
       - name: Run MSBuild
         run: msbuild .\CSharp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
